### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by u17289077** [ropensci/tif#13]
hello, i have problem 

devtools::install_github("ropensci/tif")

Error in parse(outFile) : 
  C:/Users/hugues/AppData/Local/Temp/Rtmpstb2KH/R.INSTALL2c2020bf2630/tif/R/coercion.R:177:27: unexpected ')'
176:     stop("Cannot convert object of class ", class(tokens),
177:          " to tif tokens"))
                               ^
ERROR: unable to collate and parse R files for package 'tif'
* removing 'C:/Users/hugues/Documents/R/win-library/3.5/tif'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/hugues/AppData/Local/Temp/RtmpeqtJai/file1d983bd2c12/tif_0.3.tar.gz’ had non-zero exit status

**Comment by poldham** [comment]
Hi, I have the same issue on OSX Mojave rather than Windows.

Error in parse(outFile) : 
  /private/var/folders/lz/xwyq8xyn1xz22srmd74cn1l40000gq/T/Rtmp1kbzQY/devtools1611a1a1501d9/ropensci-tif-a1cfe16/R/coercion.R:177:27: unexpected ')'
176:     stop("Cannot convert object of class ", class(tokens),
177:          " to tif tokens"))
                               ^
ERROR: unable to collate and parse R files for package ‘tif’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/tif’
Installation failed: Command failed (1)

**Comment by kbenoit** [comment]
Fixed in 5e3e18d.
